server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul
    username: shop
    password: bitc5600
    driver-class-name: com.mysql.cj.jdbc.Driver 
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB    
      
file:
  path: C:/src/springbootWork/springboot-blog/media/

